// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnhrmvtnslhqoyjhlfal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuaHJtdnRuc2xocW95amhsZmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTU3OTUsImV4cCI6MjA3MjUzMTc5NX0.U_yn0Tkml47jYZRjSSwhGG-UzixgIU3anZW1DQ3k7dE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});